management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 20s

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      shipmentService:
        baseConfig: default

      driverService:
        baseConfig: default

      authService:
        baseConfig: default

  retry:
    instances:
      shipmentService:
        maxAttempts: 3

        waitDuration: 1s

      driverService:
        maxAttempts: 3

        waitDuration: 1s

      authService:
        maxAttempts: 3

        waitDuration: 1s

  timelimiter:
    instances:
      shipmentService:
        timeoutDuration: 2s

      driverService:
        timeoutDuration: 2s

      authService:
        timeoutDuration: 2s
