# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info

#   endpoint:
#     health:
#       show-details: always

# logging:
#   level:
#     root: INFO
#     org.springframework.cloud: INFO
#     org.springframework.web: INFO

# spring:
#   jackson:
#     default-property-inclusion: non_null

spring:
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: logistics-secret-key-logistics-secret-key-logistics-secret-key
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO
