server:
  port: 8083

spring:
  application:
    name: shipment-service

  datasource:
    url: jdbc:postgresql://localhost:5434/shipment_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: logistics-secret-key-logistics-secret-key-logistics-secret-key
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.logistics.shipmentservice.client: DEBUG
    feign: DEBUG
